/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Airlineproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

 
public class AirlineWelcome extends javax.swing.JFrame 
{
    
        public static boolean AllFlightDetails = false;
        public static boolean FlightInfoAdd = false;
        public static boolean FlightDetails = false;
        public static boolean Reservation = false;
        public static boolean SearchFlight = false;
        public static boolean SeatGenerate = false;
        public static boolean PassengerDetails = false;
        public static boolean CancelBooking = false;
        
        
        

     Connection con;
    Statement stmt;
    ResultSet rs;
     
    public AirlineWelcome() 
    {
        initComponents();
        
        
         try{
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlineReservation","root","root");
             stmt = con.createStatement();
        
        
        }
        

        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuflight = new javax.swing.JMenuItem();
        menuGenerate = new javax.swing.JMenuItem();
        menuBook = new javax.swing.JMenuItem();
        menucancel = new javax.swing.JMenuItem();
        menupassenger = new javax.swing.JMenuItem();
        menusearch = new javax.swing.JMenuItem();
        menuAllFlight = new javax.swing.JMenuItem();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("DEVELOPED BY:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("AAYANK SINGHAI");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("XII B");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setText("AIRWAYS RESERVATION");

        jMenu1.setText("File");

        menuflight.setText("Flight Information ");
        menuflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuflightActionPerformed(evt);
            }
        });
        jMenu1.add(menuflight);

        menuGenerate.setText("Generate Seats");
        menuGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerateActionPerformed(evt);
            }
        });
        jMenu1.add(menuGenerate);

        menuBook.setText("Book Flight");
        menuBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBookActionPerformed(evt);
            }
        });
        jMenu1.add(menuBook);

        menucancel.setText("Cancel Booking");
        menucancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucancelActionPerformed(evt);
            }
        });
        jMenu1.add(menucancel);

        menupassenger.setText("Passenger Details");
        menupassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupassengerActionPerformed(evt);
            }
        });
        jMenu1.add(menupassenger);

        menusearch.setText("Search Flights");
        menusearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusearchActionPerformed(evt);
            }
        });
        jMenu1.add(menusearch);

        menuAllFlight.setText(" All Flights Details");
        menuAllFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAllFlightActionPerformed(evt);
            }
        });
        jMenu1.add(menuAllFlight);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel6))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuflightActionPerformed
      
       
        if (menuflight.isSelected()==false)
        {
         
            FlightInfoAdd flight = new FlightInfoAdd();
            flight.setVisible(true);
            dispose();
            FlightInfoAdd = true;
            
           
            
            
            
            
        }
        
        
        
        
        
    }//GEN-LAST:event_menuflightActionPerformed

    private void menuGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerateActionPerformed

        if (menuGenerate.isSelected()==false)
        {
         
            SeatGenerate seat = new SeatGenerate();
            seat.setVisible(true);
            dispose();
           
            
            
            
            
            
        }





    }//GEN-LAST:event_menuGenerateActionPerformed

    private void menuBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBookActionPerformed

        if(menuBook.isSelected()==false)
        {
        
            Reservation reserve = new Reservation();
            reserve.setVisible(true);
            dispose();
            Reservation = true;
            
            
        
        }




    }//GEN-LAST:event_menuBookActionPerformed

    private void menucancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucancelActionPerformed

        if(menucancel.isSelected()==false)
        {
        
            CancelBooking cancelBooking = new CancelBooking();
            cancelBooking.setVisible(true);
            dispose();
            CancelBooking = true;
        
        
        }




    }//GEN-LAST:event_menucancelActionPerformed

    private void menupassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupassengerActionPerformed

        if(menupassenger.isSelected()==false)
        {
            PassengerDetails details = new PassengerDetails();
            details.setVisible(true);
            dispose();
            PassengerDetails = true;
        
        
        }



    }//GEN-LAST:event_menupassengerActionPerformed

    private void menusearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusearchActionPerformed

        if(menusearch.isSelected()==false)
            
        {
        
            SearchFlight flight = new SearchFlight();
            flight.setVisible(true);
            dispose();
            SearchFlight = true;
        
        
        }



    }//GEN-LAST:event_menusearchActionPerformed

    private void menuAllFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAllFlightActionPerformed

        if(menuAllFlight.isSelected()==false)
        {
        
            AllFlightDetails allFlightDetails = new AllFlightDetails();
            allFlightDetails.setVisible(true);
            dispose();
            AllFlightDetails = true;
        
        
        
        }




    }//GEN-LAST:event_menuAllFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlineWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlineWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlineWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlineWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAllFlight;
    private javax.swing.JMenuItem menuBook;
    private javax.swing.JMenuItem menuGenerate;
    private javax.swing.JMenuItem menucancel;
    private javax.swing.JMenuItem menuflight;
    private javax.swing.JMenuItem menupassenger;
    private javax.swing.JMenuItem menusearch;
    // End of variables declaration//GEN-END:variables
}
