 

package Airlineproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


 
public class FlightInfoAdd extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    Statement stmt;
    
   
    public FlightInfoAdd() {
        initComponents();
        
        try{
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlineReservation","root","root");
            stmt = con.createStatement();
        
        
        }
        

        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null, e);
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFlightno = new javax.swing.JTextField();
        rdbDomestic = new javax.swing.JRadioButton();
        rdbInternational = new javax.swing.JRadioButton();
        txtType = new javax.swing.JTextField();
        rdbOne = new javax.swing.JRadioButton();
        rdbRound = new javax.swing.JRadioButton();
        rdbMulti = new javax.swing.JRadioButton();
        txtTrip = new javax.swing.JTextField();
        cmbSource = new javax.swing.JComboBox();
        cmbDestination = new javax.swing.JComboBox();
        btnLoad = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtArrival = new javax.swing.JTextField();
        txtDeparture = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("FLIGHT INFORMATION");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Departure Time");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Arrival Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Destination");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Flight No.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Source");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Trip");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Type");

        txtFlightno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        buttonGroup1.add(rdbDomestic);
        rdbDomestic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbDomestic.setText("Domestic");
        rdbDomestic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbDomesticMouseClicked(evt);
            }
        });
        rdbDomestic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDomesticActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbInternational);
        rdbInternational.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbInternational.setText("International");
        rdbInternational.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbInternationalMouseClicked(evt);
            }
        });
        rdbInternational.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbInternationalActionPerformed(evt);
            }
        });

        txtType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        buttonGroup2.add(rdbOne);
        rdbOne.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbOne.setText("One-Way");
        rdbOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbOneMouseClicked(evt);
            }
        });
        rdbOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOneActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbRound);
        rdbRound.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbRound.setText("Round-Trip");
        rdbRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbRoundMouseClicked(evt);
            }
        });
        rdbRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRoundActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbMulti);
        rdbMulti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbMulti.setText("Multi-Trip");
        rdbMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbMultiMouseClicked(evt);
            }
        });
        rdbMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMultiActionPerformed(evt);
            }
        });

        txtTrip.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        cmbSource.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Mumbai", "Delhi", "Indore", "Hyderabad", "Chennai", "Goa", "Kolkata", "Bangalore", "Chandigarh", "New York", "Chicago", "London", "Italy", "Rome", "Paris", "Sydney", "Spain" }));
        cmbSource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbSourceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbSourceMousePressed(evt);
            }
        });
        cmbSource.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                cmbSourceComponentMoved(evt);
            }
        });
        cmbSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSourceActionPerformed(evt);
            }
        });
        cmbSource.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmbSourceInputMethodTextChanged(evt);
            }
        });
        cmbSource.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbSourcePropertyChange(evt);
            }
        });

        cmbDestination.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbDestination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Mumbai", "Delhi", "Indore", "Hyderabad", "Chennai", "Goa", "Kolkata", "Bangalore", "Chandigarh", "New York", "Chicago", "London", "Italy", "Rome", "Paris", "Sydney", "Spain" }));
        cmbDestination.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDestinationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbDestinationMousePressed(evt);
            }
        });
        cmbDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDestinationActionPerformed(evt);
            }
        });
        cmbDestination.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmbDestinationInputMethodTextChanged(evt);
            }
        });
        cmbDestination.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbDestinationPropertyChange(evt);
            }
        });

        btnLoad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLoad.setText("LOAD");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnShow.setText("Show Flights");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFirst.setText("FIRST");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLast.setText("LAST");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("BACK");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtArrival.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtArrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArrivalActionPerformed(evt);
            }
        });

        txtDeparture.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtSource.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtDestination.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFlightno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdbDomestic)
                                                .addGap(55, 55, 55)
                                                .addComponent(rdbInternational)))
                                        .addGap(72, 72, 72)
                                        .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnExit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(btnPrevious))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(btnSave)))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnDelete)
                                            .addComponent(btnLast))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnClear)
                                            .addComponent(btnShow)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdbOne)
                                        .addGap(61, 61, 61)
                                        .addComponent(rdbRound)
                                        .addGap(30, 30, 30)
                                        .addComponent(rdbMulti)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cmbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(87, 87, 87)
                                            .addComponent(txtDestination, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(cmbSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(87, 87, 87)
                                            .addComponent(txtSource)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoad)
                            .addComponent(btnFirst))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNext)
                            .addComponent(btnUpdate))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFlightno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(rdbDomestic)
                            .addComponent(rdbInternational)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rdbOne)
                    .addComponent(rdbRound)
                    .addComponent(rdbMulti)
                    .addComponent(txtTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(txtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnShow))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious)
                    .addComponent(btnLast)
                    .addComponent(btnClear))
                .addGap(29, 29, 29)
                .addComponent(btnExit)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed

        try
        {
            
            String q= "Select * from Flight";
            rs= stmt.executeQuery(q);
            rs.first();
            String flight = rs.getString("Flight_No");
            String type = rs.getString("Type");
            String trip = rs.getString("Trip");
            String Source = rs.getString("Source");
            String destination = rs.getString("Destination");
            String arrival = rs.getString("ArrivalTime");
            String departure = rs.getString("DepartureTime");
            
            txtFlightno.setText(flight);
            txtTrip.setText(trip);
            txtType.setText(type);
            txtArrival.setText(arrival);
            txtDeparture.setText(departure);;
            txtDestination.setText(destination);
            txtSource.setText(Source);
         }
        
        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null,e);
        
        }












    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed

        try{
        rs.first();
            String flight = rs.getString("Flight_No");
            String type = rs.getString("Type");
            String trip = rs.getString("Trip");
            String Source = rs.getString("Source");
            String destination = rs.getString("Destination");
            String arrival = rs.getString("ArrivalTime");
            String departure = rs.getString("DepartureTime");
            
            txtFlightno.setText(flight);
            txtTrip.setText(trip);
            txtType.setText(type);
            txtArrival.setText(arrival);
            txtDeparture.setText(departure);
            txtSource.setText(Source);
            txtDestination.setText(destination);

        }
        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null, e);
        
        }



    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed

         try{
        rs.previous();
            String flight = rs.getString("Flight_No");
            String type = rs.getString("Type");
            String trip = rs.getString("Trip");
            String Source = rs.getString("Source");
            String destination = rs.getString("Destination");
            String arrival = rs.getString("ArrivalTime");
            String departure = rs.getString("DepartureTime");
            
            txtFlightno.setText(flight);
            txtTrip.setText(trip);
            txtType.setText(type);
            txtArrival.setText(arrival);
            txtDeparture.setText(departure);
            txtSource.setText(Source);
            txtDestination.setText(destination);
        }
        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null, e);
        
        }




    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed

        try{
        rs.last();
            String flight = rs.getString("Flight_No");
            String type = rs.getString("Type");
            String trip = rs.getString("Trip");
            String Source = rs.getString("Source");
            String destination = rs.getString("Destination");
            String arrival = rs.getString("ArrivalTime");
            String departure = rs.getString("DepartureTime");
            
            txtFlightno.setText(flight);
            txtTrip.setText(trip);
            txtType.setText(type);
            txtArrival.setText(arrival);
            txtDeparture.setText(departure);
            txtSource.setText(Source);
            txtDestination.setText(destination);
        }
        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null, e);
        
        }


    }//GEN-LAST:event_btnLastActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
  
      
        AirlineWelcome airlineWelcome = new AirlineWelcome();
        airlineWelcome.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        try{
        
            String flight = txtFlightno.getText();
            String types = txtType.getText();
            
            String trips = txtTrip.getText();
              String source = txtSource.getText();
              String destination = txtDestination.getText();
             String arrival = txtArrival.getText();
             String departure = txtDeparture.getText();
             
             
             String s="Select * from Flight;";
             
             String  q ="insert into Flight values('"+flight+"','"+types+"','"+trips+"','"+source+"','"+destination+"','"+arrival+"','"+departure+"')";
        
             stmt.executeUpdate(q);
             
             JOptionPane.showMessageDialog(null,"New Flight Added");
             
             txtArrival.setText("");
        txtDeparture.setText("");
        txtDestination.setText("");
        txtSource.setText("");
        txtFlightno.setText("");
        
        txtTrip.setText("");
        txtType.setText("");
        
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        
        cmbDestination.setSelectedIndex(0);
        cmbSource.setSelectedIndex(0);
        txtDestination.setText("");
        txtSource.setText("");
        
        
        
        
        
        
        }
        
        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null,e);
        
        }
        
        
        
        
        
        
        




    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtArrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArrivalActionPerformed

    private void rdbDomesticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbDomesticMouseClicked
       
        
        
        
    }//GEN-LAST:event_rdbDomesticMouseClicked

    private void rdbInternationalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbInternationalMouseClicked

        





    }//GEN-LAST:event_rdbInternationalMouseClicked

    private void rdbOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbOneMouseClicked

        

    }//GEN-LAST:event_rdbOneMouseClicked

    private void rdbRoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbRoundMouseClicked


        

    }//GEN-LAST:event_rdbRoundMouseClicked

    private void rdbMultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbMultiMouseClicked

         


    }//GEN-LAST:event_rdbMultiMouseClicked

    private void rdbInternationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbInternationalActionPerformed

        String type;
            
            if(rdbDomestic.isSelected()==true)
            {
            
                type = "Domestic";
            
            
            }
            else
            {
            
                type = "International";
            
            }
            
             txtType.setText(type);
        
        


    }//GEN-LAST:event_rdbInternationalActionPerformed

    private void cmbSourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSourceMouseClicked

        
        





    }//GEN-LAST:event_cmbSourceMouseClicked

    private void cmbDestinationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDestinationMouseClicked

        
       




    }//GEN-LAST:event_cmbDestinationMouseClicked

    private void cmbDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestinationActionPerformed

        txtDestination.setText(cmbDestination.getSelectedItem().toString());


    }//GEN-LAST:event_cmbDestinationActionPerformed

    private void cmbDestinationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDestinationMousePressed

         
       



    }//GEN-LAST:event_cmbDestinationMousePressed

    private void cmbSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSourceActionPerformed

        txtSource.setText(cmbSource.getSelectedItem().toString());


    }//GEN-LAST:event_cmbSourceActionPerformed

    private void cmbSourceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSourceMousePressed

        




    }//GEN-LAST:event_cmbSourceMousePressed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        txtArrival.setText("");
        txtDeparture.setText("");
        txtDestination.setText("");
        txtSource.setText("");
        txtFlightno.setText("");
        
        txtTrip.setText("");
        txtType.setText("");
        
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        
        cmbDestination.setSelectedIndex(0);
        cmbSource.setSelectedIndex(0);
        txtDestination.setText("");
        txtSource.setText("");
        
        




    }//GEN-LAST:event_btnClearActionPerformed

    private void txtDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinationActionPerformed

    private void cmbSourcePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbSourcePropertyChange

        



    }//GEN-LAST:event_cmbSourcePropertyChange

    private void cmbDestinationPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbDestinationPropertyChange

        



    }//GEN-LAST:event_cmbDestinationPropertyChange

    private void cmbSourceInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmbSourceInputMethodTextChanged

       
        


    }//GEN-LAST:event_cmbSourceInputMethodTextChanged

    private void cmbDestinationInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmbDestinationInputMethodTextChanged

       


    }//GEN-LAST:event_cmbDestinationInputMethodTextChanged

    private void cmbSourceComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbSourceComponentMoved
 


    }//GEN-LAST:event_cmbSourceComponentMoved

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        try{
        rs.next();
            String flight = rs.getString("Flight_No");
            String type = rs.getString("Type");
            String trip = rs.getString("Trip");
            String Source = rs.getString("Source");
            String destination = rs.getString("Destination");
            String arrival = rs.getString("ArrivalTime");
            String departure = rs.getString("DepartureTime");
            
            txtFlightno.setText(flight);
            txtTrip.setText(trip);
            txtType.setText(type);
            txtArrival.setText(arrival);
            txtDeparture.setText(departure);
            txtSource.setText(Source);
            txtDestination.setText(destination);

        }
        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null, e);
        
        }



    }//GEN-LAST:event_btnNextActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed

        FlightDetails details = new FlightDetails();
        details.setVisible(true);
        dispose();
        



    }//GEN-LAST:event_btnShowActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

         try{
        
            String flight = txtFlightno.getText();
            String types = txtType.getText();
            String trips = txtTrip.getText();
            String source = txtSource.getText();
            String destination = txtDestination.getText();
            String arrival = txtArrival.getText();
            String departure = txtDeparture.getText();
             
             
           
             
             String  q ="update Flight set Type = '"+types+"',Trip ='"+trips+"',Source = '"+source+"',Destination ='"+destination+"',ArrivalTime= '"+arrival+"',DepartureTime = '"+departure+"' where Flight_No = '"+ flight+ "'";
        
             stmt.executeUpdate(q);
             
             JOptionPane.showMessageDialog(null,"Flight Updated");
        
        
        
        
        }
        
        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null,e);
        
        }
        



    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        try{
        
            String flight = txtFlightno.getText();
          
            
            
            String qry = "delete from Flight where Flight_No =" + "'" + flight + "'";
            stmt.executeUpdate(qry);
            
            JOptionPane.showMessageDialog(null,"Flight Deleted");
        
        
        
        
        }
        
        
        catch(Exception e)
        {
        
            JOptionPane.showMessageDialog(null,e);
        
        
        }



    }//GEN-LAST:event_btnDeleteActionPerformed

    private void rdbDomesticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDomesticActionPerformed

        String type;
            
            if(rdbDomestic.isSelected()==true)
            {
            
                type = "Domestic";
            
            
            }
            else
            {
            
                type = "International";
            
            }
            txtType.setText(type);



    }//GEN-LAST:event_rdbDomesticActionPerformed

    private void rdbOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOneActionPerformed

         String trip;
            
            if(rdbOne.isSelected()==true)
            {
            
                trip = "Oneway";
               
            
            }
            else if(rdbRound.isSelected()==true)
            {
            
                trip = "Roundway";
            
            
            }
            else
            {
            
                trip ="Multiway";
                
            
            }
             txtTrip.setText(trip);


    }//GEN-LAST:event_rdbOneActionPerformed

    private void rdbRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRoundActionPerformed

         String trip;
            
            if(rdbOne.isSelected()==true)
            {
            
                trip = "Oneway";
               
            
            }
            else if(rdbRound.isSelected()==true)
            {
            
                trip = "Roundway";
            
            
            }
            else
            {
            
                trip ="Multiway";
                
            
            }
             txtTrip.setText(trip);





    }//GEN-LAST:event_rdbRoundActionPerformed

    private void rdbMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMultiActionPerformed

        String trip;
            
            if(rdbOne.isSelected()==true)
            {
            
                trip = "Oneway";
               
            
            }
            else if(rdbRound.isSelected()==true)
            {
            
                trip = "Roundway";
            
            
            }
            else
            {
            
                trip ="Multiway";
                
            
            }
             txtTrip.setText(trip);



    }//GEN-LAST:event_rdbMultiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightInfoAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmbDestination;
    private javax.swing.JComboBox cmbSource;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdbDomestic;
    private javax.swing.JRadioButton rdbInternational;
    private javax.swing.JRadioButton rdbMulti;
    private javax.swing.JRadioButton rdbOne;
    private javax.swing.JRadioButton rdbRound;
    private javax.swing.JTextField txtArrival;
    private javax.swing.JTextField txtDeparture;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFlightno;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTrip;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
